[package]
name = "yakka-motion"
version = "0.1.0"
edition = "2024"

[features]
default = ["debug-impl", "defmt"]
debug-impl = []
defmt = ["dep:defmt"]

[dependencies]
typenum = { workspace = true }
nalgebra = { workspace = true }
defmt = { workspace = true, optional = true }

yakka-number = { version = "0.1.0", path = "../yakka-number" }
