#![no_std]
//! Share peripheral access across multiple users seamlessly.
//!
//! Refer to [`resources!`] for additional information.

/// Re-exports of dependencies required by the [`resources!`] macro.
#[doc(hidden)]
pub mod reexport {
    pub use permafrost;
}

/// A trait that encodes a resource sink.
///
/// That is, an arbitrary struct type generated by [`resources!`] that is to consume the totality of the [`Resources::Source`] type.
pub trait Distributor {
    /// The source of the required resources.
    type Source;

    /// Distribute the [`resource source`] into the participants of resource sink.
    ///
    /// [`resource source`]: Resources::Source
    fn distribute(target_source: Self::Source) -> Self
    where
        Self: Sized;
}

/// A macro to deterministically assign various peripheral instances to multiple structures at once.
///
/// Once a resource sink structure has been defined, defer to [`Resources`] for further information.
#[macro_export]
macro_rules! resources {
    () => {};
    (
        $(#[$target_meta:meta])*
        for $resource_source:ty as $targe_vis:vis $target_name:ident

        $(
            $(#[$resource_meta:meta])*
            $resource_visibility:vis use $resource_name:ident become {
                $(
                    $(#[$resource_peripheral_meta:meta])*
                    $resource_peripheral_visbility:vis $resource_peripheral_name:ident => $resource_peripheral_ty:ty as $peripheral_name:ident
                ),*

                $(,)?
            }
        )*
    ) => {
        $crate::reexport::permafrost::embed!(
            $(#[$target_meta])*
            $targe_vis struct $target_name {
                $(
                    $resource_visibility [< $resource_name: >]:case{snake} $resource_name
                ),*
            }

            impl $crate::Distributor for $target_name {
                type Source = $resource_source;

                #[inline]
                fn distribute(
                    $resource_source {
                        $(
                            $(
                                $peripheral_name,
                            )*
                        )*
                        ..
                    }: $resource_source
                ) -> Self {
                    Self {
                        $(
                            [< $resource_name: >]:case{snake} $resource_name {
                                $(
                                   $resource_peripheral_name: $peripheral_name
                                ),*
                            }
                        ),*
                    }
                }
            }
        );

        $(
            $(#[$resource_meta])*
            $resource_visibility struct $resource_name {
                $(
                    $(#[$resource_peripheral_meta])*
                    $resource_peripheral_visbility $resource_peripheral_name: $resource_peripheral_ty
                ),*
            }
        )*
    };
}
