[package]
name = "yakka-log"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
embassy-time = { workspace = true }
embassy-executor = { workspace = true }
embassy-embedded-hal = { workspace = true }
embassy-futures ={ workspace = true }
embassy-net = { workspace = true }
embassy-rp = { workspace = true }
embassy-sync = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
embassy-usb-logger = "0.4.0"
