[package]
name = "yakka-motor"
version = "0.1.0"
edition = "2024"

[features]
default = ["debug-impl", "defmt"]
debug-impl = []
defmt = ["dep:defmt"]


[dependencies]
defmt = { workspace = true, optional = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
yakka-number = { version = "0.1.0", path = "../../shared/yakka-number" }
