[build]
target-dir = "../target"
target = "thumbv8m.main-none-eabihf"


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-rs run --chip RP235x"
#runner = "elf2uf2-rs -d"
runner = "picotool load -u -v -x -t elf"

[env]
DEFMT_LOG = "debug"

[alias]
test-host = "test --target=x86_64-unknown-linux-gnu"