[workspace]
resolver = "2"

members = [
    "yakka-fixpoint",
    "yakka-length",
    "yakka-motion",
    "yakka-number",
    "yakka-protocol",
    "yakka-time",
    "yakka-unit",
    "yakka-motor",
    "yakka-imu",
    "yakka-bit",
    "yakka-register",
]

[workspace.dependencies]
nalgebra = { version = "0.33.2", default-features = false }
typenum = "1.18.0"
num = { version = "0.4.3", default-features = false }
permafrost = "0.1.1"
embedded-hal = { version = "1.0.0" }
embedded-hal-async = { version = "1.0.0" }
