[workspace]
resolver = "2"

members = [
    "yakka-control",
    "yakka-flight",

    "yakka-drone",
    "yakka-log", "yakka-context", "yakka-pinout", "yakka-resource", "yakka-subsystem",
]

[workspace.dependencies]
embedded-hal = { version = "1.0.0", features = [] }
embedded-hal-async = { version = "1.0.0", features = [] }
embassy-time = { version = "0.4.0", features = [
] }
embassy-executor = { version = "0.7.0", features = [
    "task-arena-size-98304",
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
] }
embassy-embedded-hal = { version = "0.3.0", features = [] }
embassy-futures = "0.1.1"
embassy-net = { version = "0.7.0", features = [
    "tcp",
    "dhcpv4",
    "medium-ethernet",
] }
embassy-rp = { version = "0.4.0", features = [
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "rp235xa",
    "binary-info",
] }
embassy-sync = "0.6.2"
embassy-usb = "0.4.0"
cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.5"
critical-section = "1.1"

